#!/usr/bin/env python3
"""
Regenerates a stand-in for the aapt-generated R class from the real res/ XML.

Run this whenever a layout or id changes, otherwise the type-check will pass on an
R that no longer matches the resources the app actually references.
"""
import re, glob, os, sys

ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
ids, layouts, strings = set(), set(), set()

for f in glob.glob(os.path.join(ROOT, 'app/src/main/res/layout/*.xml')):
    layouts.add(os.path.basename(f)[:-4])
    for m in re.findall(r'android:id="@\+?id/([A-Za-z0-9_]+)"', open(f).read()):
        ids.add(m)

for f in glob.glob(os.path.join(ROOT, 'app/src/main/res/values/strings.xml')):
    for m in re.findall(r'<string name="([A-Za-z0-9_]+)"', open(f).read()):
        strings.add(m)

# Also pick up anything the Kotlin references, so a missing resource shows up as a
# compile error in the app rather than silently vanishing from R.
for f in glob.glob(os.path.join(ROOT, 'app/src/main/java/com/fractal/deepzoom/*.kt')):
    src = open(f).read()
    ids.update(re.findall(r'R\.id\.([A-Za-z0-9_]+)', src))
    layouts.update(re.findall(r'R\.layout\.([A-Za-z0-9_]+)', src))
    strings.update(re.findall(r'R\.string\.([A-Za-z0-9_]+)', src))


def block(name, items, start):
    out = [f"    object {name} {{"]
    out += [f"        const val {k}: Int = {start + i}" for i, k in enumerate(sorted(items))]
    out.append("    }")
    return "\n".join(out)


src = "package com.fractal.deepzoom\n\n// Generated by tools/harness/gen_r.py. Do not edit by hand.\nobject R {\n"
src += block("id", ids, 0x7f010000) + "\n"
src += block("layout", layouts, 0x7f020000) + "\n"
src += block("string", strings, 0x7f030000) + "\n}\n"

out_path = os.path.join(os.path.dirname(__file__), 'stubs', 'R.kt')
open(out_path, 'w').write(src)
print(f"wrote {out_path}: {len(ids)} ids, {len(layouts)} layouts, {len(strings)} strings")
