package com.fractal.deepzoom

// Generated by tools/harness/gen_r.py. Do not edit by hand.
object R {
    object id {
        const val c_custom: Int = 2130771968
        const val c_cycle: Int = 2130771969
        const val c_cycle_label: Int = 2130771970
        const val c_interior: Int = 2130771971
        const val c_offset: Int = 2130771972
        const val c_offset_label: Int = 2130771973
        const val c_preset: Int = 2130771974
        const val c_preset_label: Int = 2130771975
        const val c_preview: Int = 2130771976
        const val colors: Int = 2130771977
        const val controls: Int = 2130771978
        const val gl_view: Int = 2130771979
        const val goto_pos: Int = 2130771980
        const val i_aspect: Int = 2130771981
        const val i_aspect_label: Int = 2130771982
        const val i_size: Int = 2130771983
        const val i_size_label: Int = 2130771984
        const val i_summary: Int = 2130771985
        const val i_warning: Int = 2130771986
        const val iter_slider: Int = 2130771987
        const val motion_label: Int = 2130771988
        const val motion_slider: Int = 2130771989
        const val p_bar: Int = 2130771990
        const val p_label: Int = 2130771991
        const val p_sub: Int = 2130771992
        const val p_subbar: Int = 2130771993
        const val pos_input: Int = 2130771994
        const val readout: Int = 2130771995
        const val res_slider: Int = 2130771996
        const val reset: Int = 2130771997
        const val save_png: Int = 2130771998
        const val save_video: Int = 2130771999
        const val share_pos: Int = 2130772000
        const val status: Int = 2130772001
        const val v_aspect: Int = 2130772002
        const val v_aspect_label: Int = 2130772003
        const val v_dumpstrip: Int = 2130772004
        const val v_expmap: Int = 2130772005
        const val v_fps: Int = 2130772006
        const val v_fps_label: Int = 2130772007
        const val v_quality: Int = 2130772008
        const val v_quality_label: Int = 2130772009
        const val v_res: Int = 2130772010
        const val v_res_label: Int = 2130772011
        const val v_summary: Int = 2130772012
        const val v_warning: Int = 2130772013
        const val v_zoom: Int = 2130772014
        const val v_zoom_label: Int = 2130772015
        const val v_zoomin: Int = 2130772016
    }
    object layout {
        const val activity_main: Int = 2130837504
        const val dialog_image: Int = 2130837505
        const val dialog_palette: Int = 2130837506
        const val dialog_position: Int = 2130837507
        const val dialog_progress: Int = 2130837508
        const val dialog_video: Int = 2130837509
    }
    object string {
        const val app_name: Int = 2130903040
    }
}
